### ISSUE TITLE
`get_multipartite()` performance

### ISSUE THREAD

**Issue by scoavoux** [Lamarche-Perrin/triversity#1]
`get_multipartite()` is currently quite slow on large data sets.

**Comment by Lamarche-Perrin** [comment]
Could you indicate the size of your dataset (number of nodes in each part, number of edges between each couple of parts) and the total time required to load it through `get_multipartite()`?

For reference, I need 54 sec to load a tripartite containing 844,186 + 314,908 + 88 nodes and 1,358,458 + 315,978 edges on my state-of-the-art personal laptop.

**Comment by scoavoux** [comment]
My mistake, I did not use weights so my input data frame was far too long. When I use weights, I manage to get to about 45 sec with about 4k + 92k +19 nodes and 1.2M + 92k edges. For the record, it took about 10 mins without weights.
